services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${API_DB_DATABASE}
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: ${DOCKER_REPO}:${DOCKER_API_IMAGE_TAG}
    container_name: api
# Used if starting against an empty db - use once only
#    environment:
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_SQL_INIT_MODE: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

## For troubleshooting
#
#  echo-server:
#    image: mendhak/http-https-echo
#    container_name: echo
#    ports:
#      - "8080:8080"
#    environment:
#     - LOG_REQUESTS=true

volumes:
  db_data: