BEGIN;

DELETE FROM story
    USING localised_content
WHERE story.id = localised_content.story_id
  AND story.id = 1;

ALTER TABLE story
    ALTER COLUMN body_text TYPE TEXT;

ALTER TABLE story
    ADD COLUMN IF NOT EXISTS slug VARCHAR(255);

UPDATE story
    SET slug = 'backa-open',
        body_text = NULL,
        title = NULL
    WHERE id = 2;

UPDATE story
    SET slug = 'hjallbo-opens',
        body_text = NULL,
        title = NULL
    WHERE id = 3;

UPDATE story
    SET slug = 'ikea-renovation',
        body_text = NULL,
        title = NULL
    WHERE id = 4;

UPDATE story
    SET slug = '140-bikes-saved',
        body_text = NULL,
        title = NULL
    WHERE id = 5;

ALTER TABLE localised_content
    ADD COLUMN IF NOT EXISTS field_type VARCHAR(255);

UPDATE localised_content
    SET field_name = 'BODY_TEXT',
        field_type = 'RICH_TEXT',
        content = '{"plats":"Skolspåret 15","tjänster":["laga pedaler","justera växlar","kolla hjul","kontrollera lufttryck","insmörjning"],"beskrivning":"Vi erbjuder enkla reparationer på din cykel."}'
    WHERE shop_id = 1 AND lang = 'SWE';

UPDATE localised_content
SET field_name = 'BODY_TEXT',
    field_type = 'RICH_TEXT',
    content = '{"location":"Skolspåret 15","services":["fixing pedals","adjusting gears","checking tires","checking air pressure","lubrication"],"description":"We offer basic servicing of your bike."}'
WHERE shop_id = 1 AND lang = 'ENG';

UPDATE localised_content
    SET field_type = 'TEXT'
    WHERE story_id IS NULL AND shop_id IS NULL;

UPDATE localised_content
    SET content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}',
        field_type = 'RICH_TEXT'
    WHERE story_id = 2 AND lang = 'ENG';

UPDATE localised_content
    SET content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}',
        field_type = 'RICH_TEXT'
    WHERE story_id = 2 AND lang = 'SWE';

INSERT INTO localised_content
(id, lang,  field_name,  field_type,  content,  created_at,  updated_at,  created_by,  updated_by,  text_id,  shop_id,  story_id) VALUES
(161, 'ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    3),
(162,'SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    3),
(163, 'ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    4),
(164, 'SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    4),
(165, 'ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    5),
(166, 'SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    5),
(167, 'ENG', 'TITLE', 'TEXT', 'New Shop opens in Hjällbo', NOW(), NOW(), 1, 1, null, null, 3),
(168, 'SWE', 'TITLE', 'TEXT', 'Ny Butik öppnar i Hjällbo', NOW(), NOW(), 1, 1, null, null, 3),
(169, 'ENG', 'TITLE', 'TEXT', 'IKEA rebuilds our latest shop', NOW(), NOW(), 1, 1, null, null, 4),
(170, 'SWE', 'TITLE', 'TEXT', 'IKEA renoverar vår senaste butik', NOW(), NOW(), 1, 1, null, null, 4),
(171,'ENG', 'TITLE', 'TEXT', '140 bikess saved this month', NOW(), NOW(), 1, 1, null, null, 5),
(172, 'SWE', 'TITLE', 'TEXT', '140 cyklar räddade den här månaden', NOW(), NOW(), 1, 1, null, null, 5);

COMMIT;
