package se.hjulverkstan.main.feature.ticket;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import se.hjulverkstan.main.feature.notification.NotificationStatus;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class TicketStatusDto {

    @NotNull(message = "Status is required")
    private TicketStatus ticketStatus;

    // Present if notification was generated by this request – in contrast to the status of the ticket which find the
    // latest present notification from the log.
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private NotificationStatus repairCompleteNotificationStatus;
}