-- SEED Table

INSERT INTO Location
(address,           name,          location_type, comment,                     created_at,          updated_at, created_by, updated_by) VALUES
('123 Main Street', 'Hjällbo',     'SHOP',        'Sample location 1 comment', '2024-05-16 10:00:00', NOW(),      1,          1         ),
('456 Elm Street',  'Backa',       'SHOP',        'Sample location 2 comment', '2024-05-17 10:00:00', NOW(),      1,          1         ),
('789 Oak Avenue',  'Gamlestaden', 'SHOP',        'Sample location 3 comment', '2024-05-18 10:00:00', NOW(),      1,          1         ),
('101 Pine Road',   'Majorna',     'SHOP',        'Sample location 4 comment', '2024-05-19 10:00:00', NOW(),      1,          1         ),
('202 Birch Lane',  'Gamlestaden', 'SHOP',       'Sample location 5 comment', '2024-05-20 10:00:00', NOW(),      1,          1         ),
('303 Cedar Street', 'Majorna',    'SHOP',        'Sample location 6 comment', '2024-05-21 10:00:00', NOW(),      1,          1         );

--

INSERT INTO Employee
(first_name,              last_name,              phone_number,      personal_identity_number,    email,                                 created_at, updated_at, created_by, updated_by, comment                    ) VALUES
('Christopher ',          'Lo-Martire',           '+46712345678',    '19990703-9870',             'christopher.lomartire@example.com',   '2024-05-16 10:00:00',      NOW(),      1,          1,          'Sample comment 1'         ),
('Samuel',                'Siesjö',               '+46723019838',    '20010203-4567',             'samuel.siesjo@example.com',           '2024-05-18 10:00:01',      NOW(),      1,          1,          'Sample comment 2'         ),
('Jona',                  'Cwejman',              '555-111-2222',    '19720408-2288',             'jona.cqwejman@example.com',           '2024-05-17 10:00:00',      NOW(),      1,          1,          'Sample employee 3 comment'),
('Azfar',                 'Imtiaz',               '555-333-4444',    '20001224-7763',             'azfar.imtiaz@example.com',            '2024-05-19 10:00:00',      NOW(),      1,          1,          'Sample employee 4 comment');
--

INSERT INTO Customer
(customer_type,  first_name, last_name,  personal_identity_number,    organization_name,phone_number,    email,                  created_at, updated_at, created_by, updated_by) VALUES
('PERSON',       'Tuva',     'Nilsson',  '19900101-1239',             null,             '+46798382301',  'tuva@example.com',     '2024-05-16 10:00:00',      NOW(),      1,          1         ),
('PERSON',       'Emil',     'Berglund', '19851224-5674',             null,             '+46832103988',  'emil@example.com',     '2024-05-17 10:00:00',      NOW(),      1,          1         ),
('ORGANIZATION', 'Bosse',    'Boström',  '20030515-9018',             'Biltema',        '+46798381201',  'bosseboss@biltema.se', '2024-05-18 10:00:00',      NOW(),      1,          1         );

--

INSERT INTO vehicle
(location_id, vehicle_type, vehicle_status,   imageURL,            comment,                       is_customer_owned, bike_type,      gear_count, size,     brake_type,     brand,         reg_tag, created_at,            updated_at, created_by, updated_by) VALUES
(1,           'BIKE',       'ARCHIVED',       'image_url_1.jpg',   null,                          true,              'CHILD',        1,          'MEDIUM', 'DISC',         'SKEPPSHULT',  null,    '2024-05-16 10:00:00', NOW(),      1,          1         ),
(1,           'BIKE',       'AVAILABLE',      'image_url_1.jpg',   null,                          false,             'ROAD',         12,         'MEDIUM', 'DISC',         'SKEPPSHULT',  'ERTY',  '2024-05-17 10:00:00', NOW(),      1,          1         ),
(1,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          false,             'LADY',         15,         'MEDIUM', 'FOOTBRAKE',    'MONARK',      'YTLO',  '2024-05-18 10:00:00', NOW(),      1,          1         ),
(1,           'BIKE',       null,             'image_url_1.jpg',   'Can not ever be repaired...', true,              'ROAD',         12,         'MEDIUM', 'DISC',         'SKEPPSHULT',  null,    '2024-05-19 10:00:00', NOW(),      1,          1         ),
(2,           'BIKE',       null,             'image_url_1.jpg',   null,                          true,              'BMX',          1,          'MEDIUM', 'DISC',         'KRONAN',      null,    '2024-05-20 10:00:00', NOW(),      1,          1         ),
(2,           'BIKE',       'AVAILABLE',      'image_url_2.jpg',   'This bike weighs nothing!',   false,             'ROAD',         18,         'LARGE',  'CALIPER',      'KRONAN',      'ANOJ',  '2024-05-21 10:00:00', NOW(),      1,          1         ),
(2,           'BIKE',       'UNAVAILABLE',    'image_url_3.jpg',   'Bulletproof tires',           false,             'ELECTRIC',     15,         'SMALL',  'DISC',         'KRONAN',      'QWER',  '2024-05-21 10:00:00', NOW(),      1,          1         ),
(1,           'BIKE',       null,             'image_url_2.jpg',   null,                          true,              'MOUNTAINBIKE', 28,         'LARGE',  'CALIPER',      'PELAGO',      null,    '2024-06-21 10:00:00', NOW(),      1,          1         );

--

INSERT INTO Ticket
(ticket_type, ticket_status,    employee_id,  customer_id, start_date,       end_date,     comment,                 repair_description,                    created_at,            updated_at,    created_by,   updated_by)  VALUES
('REPAIR',    'CLOSED',         2,            1,           '2024-05-17',     '2024-05-20', 'Important',             'Adjust gears and lubricate',          '2024-05-16 10:00:00', NOW(),         1,            1         ),
('RENT',      'CLOSED',         1,            2,           '2024-05-16',     '2024-05-22', null                   , null,                                  '2024-05-16 10:00:00', NOW(),         1,            1         ),
('REPAIR',    'CLOSED',         2,            1,           '2024-05-20',     '2024-05-20', 'Could be back earlier', 'Flat tire front and loose handlebar', '2024-05-20 10:00:01', NOW(),         1,            1         ),
('RENT',      'IN_PROGRESS',    3,            1,           '2024-05-24',     '2024-05-28', null,                    null,                                  '2024-05-20 10:00:02', NOW(),         1,            1         ),
('RENT',      'IN_PROGRESS',    3,            2,           '2024-05-23',     '2024-05-14', 'Lets prioritise this',  null,                                  '2024-05-23 10:00:03', NOW(),         1,            1         ),
('DONATE',    null,             1,            3,           null,             null,         null,                    null,                                  '2024-06-01 10:00:08', NOW(),         1,            1         ),
('RECEIVE',   null,             2,            3,           null,             null,         null,                    null,                                  '2024-06-04 10:00:09', NOW(),         1,            1         ),
('RENT',      'IN_PROGRESS',    1,            1,           '2024-07-20',     '2026-06-06', 'I like this guy',       null,                                  '2024-07-07 10:00:10', NOW(),         1,            1         );

INSERT INTO Ticket_Vehicle
(vehicle_id, ticket_id) VALUES
(1,         1         ),
(3,         2         ),
(2,         2         ),
(2,         3         ),
(6,         4         ),
(7,         5         ),
(4,         6         ),
(8,         7         ),
(8,         8         );

--

INSERT INTO Open_Hours
(mon,               tue,               wed,               thu,               fri,               sat,               sun) VALUES
(null,              '10:00 - 18:00',   null,              '14:00 - 18:00',   null,              null,              null),
('10:00 - 18:00',   null,              '10:00 - 18:00',   null,              null,              null,              null),
('15:00 - 18:00',   '10:00 - 18:00',   '10:00 - 18:00',   '15:00 - 18:00',   null,              null,              null),
('15:00 - 18:00',   '15:00 - 18:00',   '15:00 - 18:00',   '14:00 - 18:00',   null,              null,              null),
('15:00 - 18:00',   '10:00 - 18:00',   '10:00 - 18:00',   '15:00 - 18:00',   null,              null,              null),
('15:00 - 18:00',   '15:00 - 18:00',   '15:00 - 18:00',   '15:00 - 18:00',   null,              null,              null);


INSERT INTO Shop
(name,                    address,                                         latitude,  longitude, imageURL,                                                                                    open_hours_id, has_temporary_hours, location_id, slug,           created_at, updated_at, created_by, updated_by) VALUES
('Hjällbo',               'Skolspåret 15, 424 37 Angered',                 57.769667, 12.013639, 'https://hjulverkstan.s3.eu-north-1.amazonaws.com/4414679a-3c1b-4722-bd10-f95e66723a97.jpg', 1,             false,               1,           'hjallbo',      NOW(),      NOW(),      1,          1         ),
('Backa',                 'Selma Lagerlöfs Torg 20, 422 48 Hisings Backa', 57.748000, 11.965000, 'https://hjulverkstan.s3.eu-north-1.amazonaws.com/d80043e0-2c01-4511-a6e4-f0980da04da5.jpg', 2,             false,               2,           'backa',        NOW(),      NOW(),      1,          1         ),
('Gamlestaden',           'Lars Kaggsgatan 40D, 415 04 Göteborg',          57.720700, 12.010000, 'https://hjulverkstan.s3.eu-north-1.amazonaws.com/029c60ac-e93e-4501-98e8-8c41d72d2b75.jpg', 3,             false,               3,           'gamlestaden',  NOW(),      NOW(),      1,          1         );


INSERT INTO Story
(title,                            slug,             body_text, imageurl, created_at, created_by, updated_at, updated_by) VALUES
('New Shop opens in Hjällbo',     'hjallbo-opens',   null, null, NOW(), 1, NOW(), 1),
('IKEA rebuilds our latest shop', 'ikea-renovation', null, null, NOW(), 1, NOW(), 1),
('140 bikes saved this month',    '140-bikes-saved', null, null, NOW(), 1, NOW(), 1);

INSERT INTO users
(username,       email,                     password, created_at, updated_at, created_by, updated_by                                                      ) VALUES
('christopher',  'admin@example.com',       '$2a$10$OV/brazFuYRnDqmaNKNereIvy8VK0RzZOw1ptctgw4fJLRCMckRfO', '2024-05-16 10:00:00', NOW(), 1, 2),
('user',         'user@example.com',        '$2a$10$OV/brazFuYRnDqmaNKNereIvy8VK0RzZOw1ptctgw4fJLRCMckRfO', '2024-07-17 10:00:00', NOW(), 1, 2),
('admin',        'admin2@example.com',      '$2a$10$OV/brazFuYRnDqmaNKNereIvy8VK0RzZOw1ptctgw4fJLRCMckRfO', '2024-10-18 10:00:00', NOW(), 1, 2);

--

INSERT INTO Localised_Content
(lang,  field_name,  field_type,  content,                                                                                                                                                                                                                                                                  created_at, updated_at, created_by, updated_by, text_id, shop_id, story_id) VALUES
('ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    1),
('SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    1),
('ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    2),
('SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    2),
('ENG', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Last summer"},{"type":"text","text":", we organized a guided bike tour through Gothenburg for a group of international students visiting the city for the first time. The idea was simple: show them the beauty of Gothenburg from the saddle of a bike – and let them experience the city like a local. We started in the heart of the city, where everyone picked up their rental bikes and helmets at our shop. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen. After a short safety briefing, we set off toward the leafy paths of Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.” "},{"type":"text","text":"Another was amazed at how easily they could reach both green parks and the waterfront. "}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing in the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us,"},{"type":"text","marks":[{"type":"italic"}],"text":" “I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront. Another was amazed at how easily they could reach both green parks and the waterfront."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"A gift"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Nothing to give"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Just another bike"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Anything you like"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Bicyles the way, we made several stops – for coffee, for photos, and to talk about the city’s culture, history, and hidden gems. For many of the participants, it was the highlight of their stay. One student told us, "},{"type":"text","marks":[{"type":"italic"}],"text":"“I never thought biking through a new city could feel so personal.”"},{"type":"text","text":" Another was amazed at how easily they could reach both green parks and the waterfront."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    3),
('SWE', 'BODY_TEXT', 'RICH_TEXT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Förra sommarn"},{"type":"text","text":", Vi organiserade en guidad cykeltur genom Göteborg för en grupp internationella studenter som besökte staden för första gången. Idén var enkel: visa dem Göteborgs skönhet från cykelsadeln – och låta dem uppleva staden som en lokalbo. Vi började i hjärtat av staden, där alla hämtade ut sina hyrda cyklar och hjälmar i vår butik. Efter en kort säkerhetsgenomgång begav vi oss av mot de lummiga stigarna i Slottsskogen."}]},{"type":"paragraph","content":[{"type":"text","text":"På vägen med cyklarna gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det en av höjdpunkterna under deras vistelse. En student sa till oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.” "},{"type":"text","text":"En annan blev förvånad över hur enkelt det var att ta sig både till gröna parker och till vattnet. "}]},{"type":"paragraph","content":[{"type":"text","text":"Utan något som stod i vägen gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student sa till oss,"},{"type":"text","marks":[{"type":"italic"}],"text":" “Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"En gåva"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Inget att erbjuda"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Ännu en cykel"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Vad du än vill"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Med cyklarna som färdmedel gjorde vi flera stopp – för kaffe, för att ta bilder och för att prata om stadens kultur, historia och dolda pärlor. För många av deltagarna var det höjdpunkten under deras vistelse. En student berättade för oss, "},{"type":"text","marks":[{"type":"italic"}],"text":"“Jag hade aldrig trott att det kunde kännas så personligt att cykla genom en ny stad.”"},{"type":"text","text":" En annan blev förvånad över hur lätt det var att ta sig både till gröna parker och till vattnet."}]}]}]}', NOW(),      NOW(),      1,          1,          null,    null,    3),
('ENG', 'TITLE', 'TEXT', 'New Shop opens in Hjällbo', NOW(), NOW(), 1, 1, null, null, 1),
('SWE', 'TITLE', 'TEXT', 'Ny Butik öppnar i Hjällbo', NOW(), NOW(), 1, 1, null, null, 1),
('ENG', 'TITLE', 'TEXT', 'IKEA rebuilds our latest shop', NOW(), NOW(), 1, 1, null, null, 2),
('SWE', 'TITLE', 'TEXT', 'IKEA renoverar vår senaste butik', NOW(), NOW(), 1, 1, null, null, 2),
('ENG', 'TITLE', 'TEXT', '140 bikess saved this month', NOW(), NOW(), 1, 1, null, null, 3),
('SWE', 'TITLE', 'TEXT', '140 cyklar räddade den här månaden', NOW(), NOW(), 1, 1, null, null, 3);


INSERT INTO roles
(id, name       ) VALUES
(1, 'ROLE_ADMIN'),
(2, 'ROLE_USER' ),
(3,'ROLE_PIPELINE');

INSERT INTO user_roles
(role_id, user_id) VALUES
(1,       1      ),
(2,       1      ),
(2,       2      ),
(1,       3      ),
(2,       3      );
