ALTER TABLE ticket ADD COLUMN location_id BIGINT;

UPDATE ticket t
SET location_id = (
    SELECT v.location_id
    FROM ticket_vehicle tv
             JOIN vehicle v ON v.id = tv.vehicle_id
    WHERE tv.ticket_id = t.id
      AND v.location_id IS NOT NULL
    ORDER BY tv.vehicle_id ASC
    LIMIT 1
)
WHERE t.location_id IS NULL;

CREATE TABLE notification
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    message VARCHAR(255),
    notification_status VARCHAR(255),
    notification_type VARCHAR(255),
    phone_number VARCHAR(255),
    sns_message_id VARCHAR(255),
    ticket_id BIGINT,
    CONSTRAINT fk_notification_ticket
        FOREIGN KEY (ticket_id)
            REFERENCES ticket(id)
            ON DELETE CASCADE
);