CREATE TABLE IF NOT EXISTS statistic_baseline
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statistic_key VARCHAR(255) NOT NULL UNIQUE,
    value BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS statistic
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statistic_key VARCHAR(255) NOT NULL UNIQUE,
    value BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO statistic_baseline (statistic_key, value) VALUES
('REPAIRED', 395),
('HIRED', 46),
('SAVED', 32)
ON CONFLICT (statistic_key) DO NOTHING;

INSERT INTO statistic (statistic_key, value, updated_at) VALUES
('REPAIRED', 0, NOW()),
('HIRED', 0, NOW()),
('SAVED', 0, NOW())
ON CONFLICT (statistic_key) DO NOTHING;
