--
INSERT INTO vehicle
(id, location_id, vehicle_type, vehicle_status, imageURL, comment, is_customer_owned, bike_type, gear_count, size, brake_type, brand, reg_tag, vehicle_class, created_at, updated_at, created_by, updated_by) VALUES
(1, 1,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          true,              'CHILD',        1,          'MEDIUM', 'DISC',         'SKEPPSHULT',  'ABC123',   'BIKE',          '2024-05-16 10:00:00', NOW(),      1,          1 ),
(2, 1,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          true,              'CHILD',        1,          'MEDIUM', 'DISC',         'SKEPPSHULT',  null,       'BIKE',          '2024-05-16 10:00:00', NOW(),      1,          1 ),
(3, 1,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          false,             'ROAD',         12,         'MEDIUM', 'DISC',         'SKEPPSHULT',  'ERTY',     'BIKE',          '2024-05-17 10:00:00', NOW(),      1,          1 ),
(4, 1,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          false,             'LADY',         15,         'MEDIUM', 'FOOTBRAKE',    'MONARK',      'YTLO',     'BIKE',          '2024-05-18 10:00:00', NOW(),      1,          1 ),
(5, 1,           'BIKE',       'BROKEN',         'image_url_1.jpg',   'Can not ever be repaired...', true,              'ROAD',         12,         'MEDIUM', 'DISC',         'SKEPPSHULT',  null,       'BIKE',          '2024-05-19 10:00:00', NOW(),      1,          1 ),
(6, 2,           'BIKE',       'UNAVAILABLE',    'image_url_1.jpg',   null,                          true,              'BMX',          1,          'MEDIUM', 'DISC',         'KRONAN',      null,       'BIKE',          '2024-05-20 10:00:00', NOW(),      1,          1 ),
(7, 2,           'BIKE',       'AVAILABLE',      'image_url_3.jpg',   'This bike weighs nothing!',   false,             'ROAD',         18,         'LARGE',  'CALIPER',      'KRONAN',      'ANOJ',     'BIKE',          '2024-05-21 10:00:00', NOW(),      1,          1 ),
(8, 2,           'BIKE',       'AVAILABLE',      'image_url_3.jpg',   'Bulletproof tires',           false,             'ELECTRIC',     15,         'SMALL',  'DISC',         'KRONAN',      'QWER',     'BIKE',          '2024-05-21 10:00:00', NOW(),      1,          1 ),
(9, 1,           'BIKE',       null,             'image_url_2.jpg',   null,                          true,              'MOUNTAINBIKE', 28,         'LARGE',  'CALIPER',      'PELAGO',      null,       'BIKE',          '2024-06-21 10:00:00', NOW(),      1,          1 ),
(10, 1,           'BIKE',       null,             null,                null,                          true,              'MOUNTAINBIKE', 28,         'LARGE',  'CALIPER',      'PELAGO',      null,       'BIKE',          '2024-06-23 10:00:00', NOW(),      1,          1 ),
(11, 1,           'BIKE',       null,             null,                null,                          true,              'MOUNTAINBIKE', 28,         'LARGE',  'CALIPER',      'PELAGO',      null,       'BIKE',          '2024-06-24 10:00:00', NOW(),      1,          1 ),
(12, 1,           'BIKE',       'AVAILABLE',      '',                  null,                          false,             'ROAD',         10,         'SMALL',  'DISC',         'SPECIALIZED', 'EMPTY1',   'BIKE',          '2024-06-25 10:00:00', NOW(),      1,          1 ),
(13, 1,           'BIKE',       'AVAILABLE',      'image @#%_url$.jpg',null,                          false,             'ROAD',         11,         'MEDIUM', 'DISC',         'SKEPPSHULT',  'SPEC1',    'BIKE',          '2024-06-26 10:00:00', NOW(),      1,          1 ),
(14, 1,           'BIKE',       'AVAILABLE',      'image_url_123.jpg', null,                          false,             'ROAD',         12,         'LARGE',  'DISC',         'SKEPPSHULT',  'SUBSTR1',  'BIKE',          '2024-06-27 10:00:00', NOW(),      1,          1 ),
(15, 1,           'BIKE',       'AVAILABLE',      '   ',               null,                          false,             'ROAD',         13,         'MEDIUM', 'DISC',         'SKEPPSHULT',  'WHITE1',   'BIKE',          '2024-06-28 10:00:00', NOW(),      1,          1 ),
(16, 1,           'BIKE',       'AVAILABLE',      'image_url_%.jpg',   null,                          false,             'ROAD',         15,         'LARGE',  'DISC',         'SKEPPSHULT',  'WILD1',    'BIKE',          '2024-06-30 10:00:00', NOW(),      1,          1 );
--