import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import * as jsdom from 'jsdom';

import * as C from '@utils/common';
import { logIn } from '@data/auth/api';
import { PreloadedDataProvider } from '@hooks/usePreloadedData';
import { getAllWebEditEntitiesByLang } from '@data/webedit/api';

import Root, { fallbackLocale } from '@root';
import { HelmetProvider } from 'react-helmet-async';
import { instance } from '@data/api';

export { createRoutes } from '@root';

// Setup virtual window object for tiptap to works serverside, see: [tiptap
// #3233](https://github.com/ueberdosis/tiptap/discussions/3233)

const dom = new jsdom.JSDOM('<!DOCTYPE html>');
global.window = dom.window as unknown as Window & typeof globalThis;
global.document = dom.window.document;

/**
 * Async function for getting web edit data. This is used during build (and in
 * dev server) to inject data into PreloadedDataProvider. See (link)[link]
 * for more information about this application design.
 */

export async function getDataForPreloadingServerSide(
  env: Record<string, string>,
) {
  // First add the cookie jar interceptors so that authentication cookies can
  // be stored when run on server side.

  const ejectCookieJar = C.useAxiosCookieJar(instance);

  await logIn(
    {
      username: env.VITE_BUILD_USERNAME,
      password: env.VITE_BUILD_PASSWORD,
    },
    env.VITE_BACKEND_URL,
  );

  const res = await getAllWebEditEntitiesByLang(
    { fallbackLocale },
    env.VITE_BACKEND_URL,
  );

  ejectCookieJar();
  return res;
}

/**
 * This is the function called by reactDom.renderToString when the application
 * is statically generated by the build script. See (link)[link] for more
 * information about the application architecture.
 */

export interface RenderSSRProps {
  path: string | Partial<Location>;
  helmetContext: any;
  data: Record<string, any>;
}

export function renderSSR({ path, data, helmetContext }: RenderSSRProps) {
  return ReactDOMServer.renderToString(
    <StaticRouter location={path}>
      <PreloadedDataProvider value={data}>
        <HelmetProvider context={helmetContext}>
          <Root />
        </HelmetProvider>
      </PreloadedDataProvider>
    </StaticRouter>,
  );
}
