name: Web Deploy

on:
  workflow_dispatch:

env:
  S3_BUCKET:
  CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.DEPLOY_WEB_CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: ./dist/static

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ DEPLOY_WEB_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache (optional)
        if: vars.DEPLOY_WEB_CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.DEPLOY_WEB_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"